package com.codingplatform.backend.service;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import org.springframework.stereotype.Component;

/**
 * OutputComparator is a deterministic utility component for comparing actual standard output
 * generated by candidate solutions against expected test case answers.
 *
 * <p>Supported Validation Strategies:
 *
 * <ul>
 *   <li><b>Exact Match (default)</b>: Trims whitespace and checks string equality.
 *   <li><b>Quote-Insensitive Strings</b>: Normalizes string tokens wrapped in single or double
 *       quotes (e.g. {@code "hello"} vs {@code hello}).
 *   <li><b>Unordered Arrays ({@code unordered_array})</b>: Parses array formats like {@code [0,
 *       1]}, sorts elements, and checks set equivalence (essential for algorithms like Two Sum
 *       where index ordering may vary).
 * </ul>
 */
@Component
public class OutputComparator {

    /**
     * Compares actual stdout against expected output based on the question's validator rule.
     *
     * @param actual the stdout string produced by candidate execution
     * @param expected the expected test case output
     * @param validatorType the validation rule (e.g. {@code "exact"} or {@code "unordered_array"})
     * @return true if the output satisfies the expected criteria, false otherwise
     */
    public boolean compare(String actual, String expected, String validatorType) {
        if (actual == null && expected == null) return true;
        if (actual == null || expected == null) return false;

        String normActual = actual.trim();
        String normExpected = expected.trim();

        if (normActual.equals(normExpected)) {
            return true;
        }

        // Compare after stripping outer quotes if string comparison
        String unquotedActual = stripOuterQuotes(normActual);
        String unquotedExpected = stripOuterQuotes(normExpected);
        if (unquotedActual.equals(unquotedExpected)) {
            return true;
        }

        // Check if both are arrays e.g. "[0, 1]"
        if (isArray(normActual) && isArray(normExpected)) {
            List<String> actualElements = parseArrayElements(normActual);
            List<String> expectedElements = parseArrayElements(normExpected);

            if ("unordered_array".equalsIgnoreCase(validatorType)) {
                List<String> sortedActual = new ArrayList<>(actualElements);
                List<String> sortedExpected = new ArrayList<>(expectedElements);
                Collections.sort(sortedActual);
                Collections.sort(sortedExpected);
                return sortedActual.equals(sortedExpected);
            } else {
                return actualElements.equals(expectedElements);
            }
        }

        return false;
    }

    /**
     * Checks if a normalized string has bracketed array format (e.g. {@code "[1, 2]"}).
     *
     * @param str the trimmed candidate string
     * @return true if the string is non-null and enclosed by square brackets
     */
    private boolean isArray(String str) {
        return str != null && str.startsWith("[") && str.endsWith("]");
    }

    /**
     * Parses a comma-separated bracketed array string into individual string tokens, stripping
     * surrounding whitespace and quotes.
     *
     * @param arrayStr bracketed array representation (e.g. {@code "[0, 1]"})
     * @return list of trimmed element strings
     */
    private List<String> parseArrayElements(String arrayStr) {
        String inner = arrayStr.substring(1, arrayStr.length() - 1).trim();
        if (inner.isEmpty()) {
            return List.of();
        }
        String[] parts = inner.split(",");
        List<String> elements = new ArrayList<>();
        for (String part : parts) {
            elements.add(stripOuterQuotes(part.trim()));
        }
        return elements;
    }

    /**
     * Strips enclosing single or double quotes from a string token if present.
     *
     * @param s candidate token
     * @return token without enclosing quotes
     */
    private String stripOuterQuotes(String s) {
        if (s == null) return "";
        String trimmed = s.trim();
        if ((trimmed.startsWith("\"") && trimmed.endsWith("\"") && trimmed.length() >= 2)
                || (trimmed.startsWith("'") && trimmed.endsWith("'") && trimmed.length() >= 2)) {
            return trimmed.substring(1, trimmed.length() - 1);
        }
        return trimmed;
    }
}
