spring.application.name=coding-platform-backend

execution.piston.base-url=${PISTON_BASE_URL:http://127.0.0.1:2000}
execution.piston.language=${PISTON_LANGUAGE:java}
execution.piston.version=${PISTON_VERSION:15.0.2}
execution.piston.file-name=${PISTON_FILE_NAME:Main}
execution.piston.connect-timeout-ms=${PISTON_CONNECT_TIMEOUT_MS:2000}
execution.piston.read-timeout-ms=${PISTON_READ_TIMEOUT_MS:5000}
execution.piston.run-timeout-ms=${PISTON_RUN_TIMEOUT_MS:6000}
